<?php
/**
 * @category   Auguria
 * @package    Auguria_InteractiveImage
 * @author     Auguria
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
 */

/* @var $this Auguria_InteractiveImage_Block_Adminhtml_Catalog_Product_Helper_Form_Image_Interactive_Panel_Areas */
?>
<?php
$areas = $this->getAreas();
?>

<div class="buttons">
    <button class="button btn-clear" type="button" onclick="interactiveImage.clear();">
	    <span><span><?php echo $this->__('Clear')?></span></span>
	</button>
</div>

<?php if(count($areas) > 0):?>
    <?php foreach($areas as $_area):?>
        <?php echo $this->getAreaHtml($_area)?>
    <?php endforeach;?>
<?php endif;?>
